services:
  video2x-runner:
    build: . # Build from the Dockerfile in the current directory
    container_name: video2x-runner
    volumes:
      - ./input-test:/input
      - ./output-test:/output
    runtime: nvidia
    privileged: true
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           device_ids: [ "0" ]