services:
  video2x-runner:
    build: . # Build from the Dockerfile in the current directory
    container_name: video2x-runner
    volumes:
      - /mnt/plex/Upscale/input:/input
      - /mnt/plex/Upscale/output:/output
    user: 1001:1001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: [ "0" ]