name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mdbook/${{ github.event.repository.name }}:${{ github.sha }}
                  ${{ github.ref == 'refs/heads/main' && format('ghcr.io/mdbook/{0}:latest', github.event.repository.name) || format('ghcr.io/mdbook/{0}:{1}', github.event.repository.name, github.ref_name) }}